# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'BenMachine'

steps:
- script: echo Starting Pipeline!
  displayName: 'Run a one-line script'
- script: oc status
  displayName: 'Test oc'
- script: |
    oc delete all --selector app=dot-net-example --ignore-not-found
    oc delete bc dot-net-example --ignore-not-found
  displayName: 'Clean up previous'
- script: |
    oc new-build --name dot-net-example --binary --strategy source --image-stream dotnet:3.1 
  displayName: 'Create a new build for an OpenShift s2i build'
- script: |
    oc start-build dot-net-example --from-dir . --follow 
  displayName: 'Run the build and '
- script: |
    oc new-app dot-net-example
  displayName: 'Create a new application'
