# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'BenMachine'

steps:
- script: echo Starting Pipeline!
  displayName: 'Run a one-line script'
- script: oc status
  displayName: 'Test oc'
- script: |
    oc delete deployment,svc,route --selector app=dot-net-example --ignore-not-found
    oc delete bc dot-net-example --ignore-not-found
  displayName: 'Clean up previous'
- script: oc new-build --name dot-net-example --binary --strategy source --image-stream dotnet:3.1 --env DOTNET_STARTUP_PROJECT=app/tmp.csproj
  displayName: 'Create a new build for an OpenShift s2i build'
- script: oc start-build dot-net-example --from-dir . --follow 
  displayName: 'Run the build'
- script:  skopeo copy --dest-creds=$ACR_USER:$ACR_PASSWORD --src-creds=`oc whoami`:`oc whoami -t` --tls-verify=false docker://image-registry.openshift-image-registry.svc:5000/azdevops/dot-net-example docker://bfdemorepo.azurecr.io/dot-net-example
  env:
    ACR_PASSWORD: $(acr-password)
    ACR_USER: $(acr-user)
  displayName: 'Store image in Azure Container Registry for backup'
- script: oc new-app dot-net-example
  displayName: 'Create a new application'
- script: oc expose svc/dot-net-example
  displayName: 'Expose service'
