# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'BenMachine'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: |
    oc new-app dotnet:3.1~https://github.com/redhat-developer/s2i-dotnetcore-ex#dotnetcore-3.1 --context-dir app --follow
  displayName: 'Create a new application'
- script: |
    oc expose service s2i-dotnetcore-ex --follow
  displayName: 'Expose the service as a route'
- script: |
    oc get route s2i-dotnetcore-ex --follow
  displayName: 'Display the route'
